import { defineStore } from "pinia";
import { Vector4, Mesh } from "three";

export const useGlobalConfig = defineStore("app", {
  state: () => ({
    maxWidth: 2000,
    debugTexture: false,
    particleVisible: false,
    isLocal: false,
    isUseAsr: false,
    faceDepthMin: 0,
    faceDepthMax: 0,
    // 是否使用人脸识别
    useFaceDetection: true,
    isUseHalf: false,
    isFaceReady: false,
    isFaceLamkmardUpdate: false,
    helperLineVisible: false,
    helperMeshVisible: false,
    helperPointVisible: false,
    globalDepthTextureUrl: "/src/assets/jialuoDepth2.png",
    cameraPosition: [0, 0, 177],
    // cameraPosition: [0, 0, 1063],

    faceGeometry: null,
    isUseGlobalDepth: true,
    isRenderDepth: false,
    eyeBall: new Vector4(),
    drawFaceDetection: false,

    faceAera: new Vector4(),
    particleNumber: 300,
    digitalMesh: new Mesh(),
    hasFaceInfo: false,
    config: {
      // tolerance: 0.4,
      // feathering: 0.2,
      tolerance: 0.21,
      feathering: 0.15,
      depthScale: 0.5,
      lod: 3.0,
      edgeColor: 0x57a6dc,
      keyColor: 0x00ff00,
      offset: 0.2,
      bias: -0.4,
      scale: 1.1,
      power: 0.7,
      normalThreshold: 0.0,
      rainColor: 0xcbff,
      strength: 1.5,
      radius: 0.99,
      threshold: 0.01,
    },
  }),
});
